/* --------------------------------------------------------------------------------
 #
 #  4DPlugin-GS.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : GS
 #	author : miyako
 #	2020/05/15
 #  
 # --------------------------------------------------------------------------------*/

#include "4DPlugin-GS.h"
#include <mutex>

#pragma mark -

/* Ghostscript supports exactly one instance per process (see iapi.h's own
   warning comments on gsapi_new_instance/gsapi_delete_instance). manifest.json
   declares GS as threadSafe, so 4D may call it from more than one thread at
   once; this mutex makes overlapping calls serialize -- one at a time, in
   whatever order they arrive -- instead of the second gsapi_new_instance()
   failing outright while the first call's instance is still alive. */
static std::mutex gGSInstanceMutex;

void PluginMain(PA_long32 selector, PA_PluginParameters params) {
    
	try
	{
        switch(selector)
        {
			// --- GS
            
			case 1 :
				GS(params);
				break;

        }

	}
	catch(...)
	{

	}
}

#pragma mark -

void GS(PA_PluginParameters params) {

    sLONG_PTR *pResult = (sLONG_PTR *)params->fResult;
    PackagePtr pParams = (PackagePtr)params->fParameters;

    C_LONGINT returnValue;
    returnValue.setIntValue(-1);
    /* Default/error value. Covers three paths that previously left returnValue
       unset (silently reporting 0/"success" to 4D):
         - an exception thrown anywhere below (caught below, before setReturn)
         - an empty options array (gsargc == 0)
         - gsapi_new_instance() failing (e.g. an instance already exists --
           Ghostscript supports only one instance process-wide, see iapi.h) */

    try
    {
        ARRAY_TEXT Param1;

        Param1.fromParamAtIndex(pParams, 1);

        void *minst = NULL;/* must be initialised to NULL, else crash */

    #if VERSIONMAC
        std::vector<std::string>_gsargv;
    #else
        std::vector<std::wstring>_gsargv;
    #endif

        std::vector<char *>gsargv;

        for(unsigned int i = 0;i < Param1.getSize();++i)
        {
    #if VERSIONMAC
            std::string _argv;
            CUTF8String _u8;
            Param1.copyUTF8StringAtIndex(&_u8, i);
            _argv = std::string((const char *)_u8.c_str(), _u8.length());
    #else
            std::wstring _argv;
            CUTF16String _u16;
            Param1.copyUTF16StringAtIndex(&_u16, i);
            _argv = std::wstring((const wchar_t *)_u16.c_str(), _u16.length());
    #endif
            _gsargv.push_back(_argv);

        }

        for(unsigned int i = 0;i < Param1.getSize();++i)
        {
            gsargv.push_back((char *)(_gsargv.at(i).c_str()));
        }

        int gsargc = (int)gsargv.size();

        /* Guard against &gsargv[0]/UB on an empty options array -- calling
           GS with no arguments is not meaningful, so it's treated as an
           error rather than passed through to gsapi_init_with_args(). */
        if(gsargc > 0)
        {
            /* Serialize the entire new_instance/init_with_args/exit/delete_instance
               lifecycle -- Ghostscript's single-instance restriction applies for as
               long as an instance is alive, not just at creation, so the lock must
               cover the whole block, not just the gsapi_new_instance() call. */
            std::lock_guard<std::mutex> gsInstanceLock(gGSInstanceMutex);

            if(gsapi_new_instance(&minst, NULL) == 0)
            {
    #if VERSIONMAC
                gsapi_set_arg_encoding(minst, GS_ARG_ENCODING_UTF8);
    #else
                gsapi_set_arg_encoding(minst, GS_ARG_ENCODING_UTF16LE);
    #endif

                returnValue.setIntValue(gsapi_init_with_args(minst, gsargc, gsargv.data()));

                gsapi_exit(minst);//finalises the output
                gsapi_delete_instance(minst);
            }
            /* else: gsapi_new_instance() failed despite the lock above -- this
               would now indicate something other than a same-process race (e.g.
               a prior call's instance wasn't cleanly deleted) -- returnValue
               keeps the -1 default set above instead of silently reporting
               0/success. */
        }
    }
    catch(...)
    {
        /* returnValue keeps the -1 default set above. The important part is
           falling through to setReturn() below on every path, including this
           one -- without it, 4D would be left waiting for a return value that
           never arrives (GS is declared with a return type in manifest.json:
           "GS(&Y):L"), which is a freeze, not just a missed error code. */
    }

    returnValue.setReturn(pResult);
}

