/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : GS
 #	author : miyako
 #	2017/07/22
 #
 # --------------------------------------------------------------------------------*/

#include "iapi.h"
#include "ierrors.h"

// --- Ghostscript
void GS(sLONG_PTR *pResult, PackagePtr pParams);
